import React, { forwardRef } from 'react';
import ReactMarkdown from 'react-markdown';

const PrescriptionTemplate = forwardRef(({ content }, ref) => {
  return (
    <div style={{ display: 'none' }}>
      <div 
        ref={ref} 
        style={{
          padding: '40px',
          width: '800px', // A4 approximate width
          backgroundColor: '#ffffff',
          color: '#1e293b',
          fontFamily: 'sans-serif',
          lineHeight: '1.6'
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '2px solid #3b82f6', paddingBottom: '20px', marginBottom: '20px' }}>
          <div>
            <h1 style={{ margin: 0, color: '#1e3a8a', fontSize: '28px', fontWeight: 'bold' }}>Dr. Aegis</h1>
            <p style={{ margin: 0, color: '#64748b', fontSize: '14px' }}>AI Medical Avatar | Aegis Digital Health</p>
            <p style={{ margin: 0, color: '#64748b', fontSize: '14px' }}>Virtual Consultation Report</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p style={{ margin: 0, fontWeight: 'bold' }}>Date: {new Date().toLocaleDateString()}</p>
            <p style={{ margin: 0, color: '#64748b' }}>Time: {new Date().toLocaleTimeString()}</p>
          </div>
        </div>

        {/* Markdown Content (SOAP Note or Report) */}
        <div className="prose prose-sm max-w-none prose-blue">
          <ReactMarkdown>{content}</ReactMarkdown>
        </div>

        {/* Footer & Disclaimer */}
        <div style={{ marginTop: '50px', borderTop: '1px dashed #cbd5e1', paddingTop: '20px', fontSize: '12px', color: '#64748b' }}>
          <p style={{ fontWeight: 'bold', color: '#ef4444' }}>⚠️ LEGAL & MEDICAL DISCLAIMER</p>
          <p>
            This document was auto-generated by an Artificial Intelligence system (Dr. Aegis). It is strictly for informational and digital triage purposes. 
            <strong> This is NOT a certified medical prescription, diagnosis, or legal medical record.</strong> 
            The AI is not a licensed physical practitioner. Always consult a certified physical doctor or visit a hospital for medical treatment. 
            Do not use this to purchase prescription-only medication. In case of emergency, contact local emergency services immediately.
          </p>
          <p style={{ textAlign: 'center', marginTop: '20px' }}>Generated by Aegis EMR 🚀</p>
        </div>
      </div>
    </div>
  );
});

export default PrescriptionTemplate;
